### ISSUE TITLE
CEF does not compile on MacOS 15.0.1

### ISSUE THREAD

**Issue by noituri** [software-mansion/live-compositor#825]
MacOS: 15.0.1

```
  /.../live_compositor/target/debug/build/chromium_sys-776fb27b50280eb1/out/cef_root/libcef_dll/shutdown_checker.cc:7:10: fatal error: 'atomic' file not found
      7 | #include <atomic>
```

**Comment by noituri** [comment]
Had to reinstall Command Line Tools:
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```
